export const allDescriptions = {
    sourdoughJack : "You claim you’re not hungry, but that’s before you read about a 100% beef patty seasoned as it grills topped with hickory smoked bacon, tomato, Swiss-style cheese, real mayonnaise, and ketchup – All on a toasted sourdough bread. One more time for emphasis. Toasted. Sourdough. Bread. See? Now you’re hungry.",
    classicButteryJack: "Melted garlic herb butter on a 100% beef patty seasoned as it grills. Need we say more? Nay. But we will anyway. Because this beautiful burger has all the fixins’ – Swiss Cheese, ketchup, mayo, iceberg lettuce and fresh sliced tomatoes, all on our buttery signature bun. Need we say more? Nay. For real, this time.",
    baconButteryJack: "Sometimes, a burger comes along that makes other burgers whimper in fear. This is that burger. Because this 100% beef patty seasoned as it grills is topped with melted herb butter, hickory smoked bacon, Swiss cheese, and creamy bacon mayo – and it’s all on our buttery signature bun. Don’t apologize, it’d be weirder if you weren’t drooling right now.",
    doubleJack: "This isn’t just a burger. This is a Declaration of Delicious. Two juicy, 100% beef patties seasoned as it grills with American Cheese, fresh sliced tomatoes, hand leafed lettuce, and real mayonnaise – all on a buttery bakery bun. Yeah, Great Britain wishes they could get their hands on this amazing piece of America.",
    ultimateCheeseburger: "Can a cheeseburger change the world? Nah. Don’t be silly. But an Ultimate Cheeseburger? With two 100% beef patties seasoned as they grill, American and Swiss-style cheeses, real mayonnaise, mustard, and ketchup on a buttery bakery bun? That can change the world, alright. And maybe Mars. And perhaps that planet with the cool rings around it.",
    baconUltimateCheeseburger: "How do you make an Ultimate Cheeseburger – with two 100% beef patties seasoned they grill, Hickory Smoked Bacon strips American and Swiss-style cheese, real mayonnaise, mustard, ketchup, all on a buttery bakery bun – even more ultimate? You add three slices of bacon. You read that correctly. Three. Whoever coined “three’s a crowd” has obviously never had this burger.",
    jumboJackCheeseBurger: "How do you make an Ultimate Cheeseburger – with two 100% beef patties seasoned they grill, Hickory Smoked Bacon strips American and Swiss-style cheese, real mayonnaise, mustard, ketchup, all on a buttery bakery bun – even more ultimate? You add three slices of bacon. You read that correctly. Three. Whoever coined “three’s a crowd” has obviously never had this burger.",
    jumboJack: "When you pick up the Jumbo Jack – made with a 100% beef patty seasoned as it grills topped with hand leafed lettuce, tomato, pickles, chopped onions, real mayonnaise and ketchup on a buttery bakery bun – your arms will tremble. And your mouth with open. It’s the delicious type of workout.",
    jrJumboJack: "Anywhere else this Jr. Jack would be a senior. Because the is nothing junior about this honest-to-goodness 100% beef patty seasoned as it’s grilled topped with tomato, pickle, lettuce, and chopped onions – with the just-right amount of ketchup and real mayonnaise. But here? It’s got some growing up to do.",
    jrJumboJackCheeseburger: "Anywhere else this Jr. Jack would be senior. Because there is nothing junior about this honest-to-goodness 100% beef patty seasoned as it grills topped with American cheese, tomato, pickle, lettuce, and chopped onions--with the just-right amount of ketchup and real mayonnaise. But here? It's got some growing up to do.",
    jrBaconCheeseburger: "You ever call something “junior” ironically? Well, if you haven’t you’re about to. Because this Jr. Bacon Cheeseburger is a 100% beef patty seasoned as it grills topped with hickory smoked bacon, American cheese, real mayonnaise, and ketchup. And now you have a “junior” appetite. See what we did there?"
}